### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by hjing100** [beyondguo/LLM-Tuning#59]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1184, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 62, in <module>
    from .document_question_answering import DocumentQuestionAnsweringPipeline
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/pipelines/document_question_answering.py", line 29, in <module>
    from .question_answering import select_starts_ends
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/pipelines/question_answering.py", line 9, in <module>
    from ..data import SquadExample, SquadFeatures, squad_convert_examples_to_features
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/data/__init__.py", line 26, in <module>
    from .metrics import glue_compute_metrics, xnli_compute_metrics
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/data/metrics/__init__.py", line 20, in <module>
    from sklearn.metrics import f1_score, matthews_corrcoef
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__init__.py", line 83, in <module>
    from . import (
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__check_build:
__init__.py               _check_build.cpython-39-x86_64-linux-gnu.so__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/zhj/projects/LLM-Tuning-master/RLHF/reward_modeling.py", line 11, in <module>
    import evaluate
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/evaluate/__init__.py", line 29, in <module>
    from .evaluation_suite import EvaluationSuite
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/evaluate/evaluation_suite/__init__.py", line 10, in <module>
    from ..evaluator import evaluator
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/evaluate/evaluator/__init__.py", line 27, in <module>
    from .audio_classification import AudioClassificationEvaluator
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/evaluate/evaluator/audio_classification.py", line 23, in <module>
    from .base import EVALUATOR_COMPUTE_RETURN_DOCSTRING, EVALUTOR_COMPUTE_START_DOCSTRING, Evaluator
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/evaluate/evaluator/base.py", line 34, in <module>
    from transformers import Pipeline, pipeline
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1174, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1186, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /usr/local/anaconda3/envs/test39/lib/python3.9/site-packages/sklearn/__check_build:
__init__.py               _check_build.cpython-39-x86_64-linux-gnu.so__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

说明：
最开始是：accuracy = evaluate.load("accuracy")报错
按照了accuracy，还是报错，就自己下载了https://github.com/huggingface/datasets/tree/main/metrics下载了accuracy
但是报错没有sklearn
pip install scikit-learn
然后就报以上错误，请问有人遇到过吗？

**Comment by hjing100** [comment]
解决方案：升级glibc版本到2.23。
